"""
Email Sender — Week 3

Sends test result summary + HTML report attachment via Gmail SMTP (free).
Credentials are read from environment variables — never hardcoded.

Required env vars when email.enabled = true:
  SMTP_PASSWORD  (or whatever key is set in config.email.password_env)
"""

from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any


_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body {{ font-family: Arial, sans-serif; color: #333; }}
  .summary {{ background: #f5f5f5; padding: 16px; border-radius: 6px; }}
  .pass {{ color: #2e7d32; font-weight: bold; }}
  .fail {{ color: #c62828; font-weight: bold; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 12px; }}
  th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
  th {{ background: #eeeeee; }}
</style></head>
<body>
<h2>🧪 Auto TC Report — {timestamp}</h2>
<div class="summary">
  <p>Total: <strong>{total}</strong> &nbsp;|&nbsp;
     <span class="pass">Passed: {passed}</span> &nbsp;|&nbsp;
     <span class="fail">Failed: {failed}</span> &nbsp;|&nbsp;
     Duration: {duration}s
  </p>
  <p>Source: <code>{source}</code></p>
</div>

{failed_table}

<p style="color:#888;font-size:12px;">Generated by AutoTCAgent</p>
</body>
</html>
"""

_FAILED_ROW = "<tr><td>{nodeid}</td><td><pre>{longrepr}</pre></td></tr>"


class EmailSender:
    def __init__(self, config: dict):
        email_cfg = config.get("email", {})
        self.enabled: bool = email_cfg.get("enabled", False)
        self.smtp_host: str = email_cfg.get("smtp_host", "smtp.gmail.com")
        self.smtp_port: int = int(email_cfg.get("smtp_port", 587))
        self.sender: str = email_cfg.get("sender", "")
        self.password_env: str = email_cfg.get("password_env", "SMTP_PASSWORD")
        self.recipients: list[str] = email_cfg.get("recipients", [])
        self.attach_report: bool = email_cfg.get("attach_report", True)

    def send_report(
        self,
        test_summary: dict[str, Any],
        source_label: str = "",
        html_report_path: str | Path | None = None,
    ) -> bool:
        """Send result email. Returns True on success, False otherwise."""
        if not self.enabled:
            print("[Email] Notifications disabled — skipping.")
            return False

        password = os.environ.get(self.password_env, "")
        if not password:
            print(f"[Email] {self.password_env} not set — skipping email.")
            return False

        msg = self._build_message(test_summary, source_label, html_report_path)

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as smtp:
                smtp.starttls()
                smtp.login(self.sender, password)
                smtp.sendmail(self.sender, self.recipients, msg.as_string())
            print(f"[Email] Report sent to: {', '.join(self.recipients)}")
            return True
        except Exception as e:
            print(f"[Email] Failed to send: {e}")
            return False

    # ─── internal ─────────────────────────────────────────────────────────────

    def _build_message(
        self,
        summary: dict[str, Any],
        source_label: str,
        html_report_path: str | Path | None,
    ) -> MIMEMultipart:
        msg = MIMEMultipart("mixed")
        msg["From"] = self.sender
        msg["To"] = ", ".join(self.recipients)

        passed = summary.get("passed", 0)
        failed = summary.get("failed", 0)
        status_icon = "✅" if failed == 0 else "❌"
        msg["Subject"] = f"{status_icon} TC Report — {passed}✓ {failed}✗ — {source_label or 'auto'}"

        failed_tests = summary.get("failed_tests", [])
        failed_rows = "".join(
            _FAILED_ROW.format(
                nodeid=t.get("nodeid", ""),
                longrepr=str(t.get("longrepr", ""))[:500],
            )
            for t in failed_tests
        )
        failed_table = (
            f"<h3>Failed Tests</h3><table><tr><th>Test</th><th>Reason</th></tr>{failed_rows}</table>"
            if failed_rows else "<p>No failures 🎉</p>"
        )

        body_html = _HTML_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            total=summary.get("total", 0),
            passed=passed,
            failed=failed,
            duration=summary.get("duration_seconds", 0),
            source=source_label,
            failed_table=failed_table,
        )
        msg.attach(MIMEText(body_html, "html", "utf-8"))

        if self.attach_report and html_report_path:
            report_path = Path(html_report_path)
            if report_path.exists():
                with open(report_path, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f'attachment; filename="{report_path.name}"',
                )
                msg.attach(part)

        return msg
