"""
make_raw_b64.py  —  tests/fixtures/ 이미지를 Raw RGB base64로 변환

용도:
    /api/v2/all-in-one, /api/v2/multi-detect 처럼 raw RGB bytes를 받는
    엔드포인트의 테스트 데이터 생성.

사용법:
    # 모든 이미지 출력
    python tests/fixtures/make_raw_b64.py

    # 특정 파일만
    python tests/fixtures/make_raw_b64.py face_320x240.jpg

    # --save  →  tests/fixtures/raw_b64_cache.py 로 저장 (pytest에서 import 가능)
    python tests/fixtures/make_raw_b64.py --save

출력 형식:
    width / height / channel / raw_bytes_len / base64_string
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path

FIXTURES_DIR = Path(__file__).parent

# 지원 확장자
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp"}


def to_raw_b64(img_path: Path) -> dict:
    """JPEG/PNG → RGB raw bytes → base64."""
    try:
        from PIL import Image
    except ImportError:
        sys.exit("[ERROR] Pillow가 설치되어 있지 않습니다.  pip install Pillow")

    with Image.open(img_path) as img:
        rgb = img.convert("RGB")
        raw_bytes = rgb.tobytes()
        b64_str = base64.b64encode(raw_bytes).decode("ascii")

    return {
        "file":       img_path.name,
        "width":      rgb.width,
        "height":     rgb.height,
        "channel":    3,
        "raw_bytes":  len(raw_bytes),
        "b64":        b64_str,
    }


def find_images(target: str | None) -> list[Path]:
    if target:
        p = FIXTURES_DIR / target
        if not p.exists():
            sys.exit(f"[ERROR] 파일을 찾을 수 없습니다: {p}")
        return [p]
    return sorted(p for p in FIXTURES_DIR.iterdir() if p.suffix.lower() in IMAGE_EXTS)


def print_result(info: dict) -> None:
    print(f"\n{'=' * 60}")
    print(f"  파일    : {info['file']}")
    print(f"  width   : {info['width']}")
    print(f"  height  : {info['height']}")
    print(f"  channel : {info['channel']}")
    print(f"  raw bytes: {info['raw_bytes']:,}")
    print(f"  base64  : {info['b64'][:80]}...  (총 {len(info['b64'])} chars)")


def save_cache(results: list[dict]) -> None:
    out = FIXTURES_DIR / "raw_b64_cache.py"
    lines = [
        '"""',
        'Auto-generated by make_raw_b64.py',
        'Raw RGB base64 캐시 — /api/v2/all-in-one, /api/v2/multi-detect 전용',
        '"""',
        "# fmt: off",
        "",
    ]
    for r in results:
        var_name = Path(r["file"]).stem.replace("-", "_").replace(" ", "_")
        lines += [
            f"# {r['file']}  ({r['width']}x{r['height']}x{r['channel']}  {r['raw_bytes']:,} bytes)",
            f"RAW_B64_{var_name.upper()} = {{",
            f'    "width":    {r["width"]},',
            f'    "height":   {r["height"]},',
            f'    "channel":  {r["channel"]},',
            f'    "image_data": "{r["b64"]}",',
            f"}}",
            "",
        ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n[저장 완료] {out}")
    print("사용 예:")
    if results:
        var = Path(results[0]["file"]).stem.replace("-", "_").replace(" ", "_").upper()
        print(f"  from tests.fixtures.raw_b64_cache import RAW_B64_{var}")
        print(f'  body = {{**RAW_B64_{var}}}')
        print(f'  resp = requests.post(base_url + "/api/v2/all-in-one", json=body)')


def main() -> None:
    parser = argparse.ArgumentParser(description="이미지 → Raw RGB base64 변환")
    parser.add_argument("file", nargs="?", help="변환할 파일명 (생략 시 전체)")
    parser.add_argument("--save", action="store_true", help="raw_b64_cache.py로 저장")
    args = parser.parse_args()

    images = find_images(args.file)
    if not images:
        sys.exit(f"[ERROR] {FIXTURES_DIR} 에 이미지 파일이 없습니다.")

    results = []
    for img_path in images:
        info = to_raw_b64(img_path)
        print_result(info)
        results.append(info)

    if args.save:
        save_cache(results)


if __name__ == "__main__":
    main()
